### ISSUE TITLE
Guidance on InviteAccounts step

### ISSUE THREAD

**Issue by cnoble40-netrist** [awslabs/compliant-framework-for-federal-and-dod-workloads-in-aws-govcloud-us#12]
I'm stuck. I've got a commercial account and a govcloud account. I have an existing organization setup in the commercial account (which may or may not be the problem -- with the commercial management account as a member). 
When I launch the stack, it gets all the way through to the InviteAccounts step function and then throws error:

"An error occurred (HandshakeConstraintViolationException) when calling the InviteAccountToOrganization operation: You have exceeded the allowed number of AWS accounts"

I understand what the message says, but from what I understand there can be 10 accounts (default) per organization. So, it really is not making sense to me.

Should I not have any organizations setup before launching the stack? Should I have the govcloud central account be a member of the commercial organization? There's really no mention of the actual prereq for organization structure.

Any help would be great!

**Comment by hitachiman** [comment]
On the accounts, No  run the script first to create the environment then add accounts. govcloud and commercial should not be intermixed.

**Comment by cnoble40-netrist** [comment]
I appreciate the feedback, but the issue ended up being that when they (AWS) setup my Central GovCloud account, they did not give me enough quota for adding accounts to organizations. Supposed to be 10 by default, but it was set at 2.
