### ISSUE TITLE
Guidance for adding a Tenant Account

### ISSUE THREAD

**Issue by vennemp** [awslabs/compliant-framework-for-federal-and-dod-workloads-in-aws-govcloud-us#2]
Do you have any documentation or examples on how to add a tenant account to the framework?  We framework deployed and it configured all the guardrails etc in govcloud seamlessly.  Looking to add a tenant account which will host an application vpc, eks etc.  We can handle the cdk implementation but just need to know the places to change the config in framework to streamline.

**Comment by rgd11** [comment]
The framework provides a GovCloud Account Vending Machine (AVM) through AWS Service Catalog that can be executed from the Commercial Organizations Root (Commercial-Central Account) to generate new Tenant accounts. One of the input parameters is the OU (in GovCloud) to assign the new tenant into - usually environment-<region>-tenants OU. Accounts added to the environment OU will have security baseline stacks deployed through CloudFormation Stack Sets. After an account is made, a customer can then generate workload VPCs using a separate AWS Service Catalog Product available in the GovCloud Management Services Account.  These new VPCs will be connected to the Transit Gateway and associated with the internal-tgw-rt.

**Comment by vennemp** [comment]
Thanks for the quick response!
